name: cnndm
hf_name: cnn_dailymail
hf_config: "3.0.0"
text_column: article
summary_column: highlights
max_input_length: 512
max_sentences: 50
train_split: train
val_split: validation
test_split: test
